### ISSUE TITLE
accept suggestion by pressing [ENTER]

### ISSUE THREAD

**Issue by feromax** [opto/nostalgy-xpi#49] opened 2020-11-22 02:27 UTC
First, thank you for your work on this rewrite of the original Nostalgy, which I have found indispensable.

When I want to move (save) a message to a folder and start typing the folder name, the dialog box has my typing thus far, followed by ` >> `, followed by the suggested folder path.  For example, if I type `mis`, I might see this in the dialog box:
```
mis >> Inbox/Miscellaneous
``` 
Under legacy Nostalgy, If that suggested completion is correct, I would press [ENTER] for it to be accepted and not have to press the up arrow to find the match and then press [ENTER].  

I've made two changes to `chrome/content/scripts/me-messageWindow.js` to restore this functionality:  
1.  Added helper function `RemoveUserChars()` that removes prefix `mis >> ` (as in my example above).
2.  Added a single statement to `NostalgyRunCommand()` to call the new helper function.

```
// NEW FUNCTION
function RemoveUserChars(dialogText) {
  gtIdx = dialogText.indexOf(">>");
  if ( gtIdx == -1 ) {
    return dialogText;
  }

  // dialogText may be 'mis >> Inbox/Miscellaneous'; return from 'Inbox...'
  if ( gtIdx + 3 < dialogText.length ) {
    return dialogText.substr(gtIdx + 3);
  }

  return dialogText;
}


// ADDED NEW LINE BELOW
function NostalgyRunCommand() {
  NostalgyHide(true);
  var s = nostalgy_folderBox.value;
  s = RemoveUserChars(s);                // NEW LINE
  var f = NostalgyResolveFolder(s);
```

I would have submitted a PR, but the repo only has the archive of the extension rather than its source code ;)

Cheers,
Mike

**Comment by feromax** [comment] 2020-11-22 02:32
In this scenario, where I've typed `mis`, I now merely press [ENTER] for the suggested completion to be used.
<img width="618" alt="dialogbox with suggested completion" src="https://user-images.githubusercontent.com/6591646/99892246-d7c09000-2c27-11eb-8945-c5638d07a912.png">

**Comment by opto** [comment] 2020-11-23 10:35
shortcut:  tab + enter instead changing code.

Is already resolved, will come this week as xpi. Thanks for your suggestion!!  Klaus

**Comment by opto** [comment] 2020-11-23 10:37
duplicate of #32

**Closed by opto** 2020-11-23 10:37 UTC
Labels: duplicate
