### ISSUE TITLE
Shortcuts not working when viewing message

### ISSUE THREAD

**Issue by tonysirna** [opto/nostalgy-xpi#122] opened 2021-07-28 22:33 UTC
When I'm in my inbox I can use nostalgy shortcut keys fine. When I'm in a tab viewing a message they do not seem to work at all.

I've tried creating a custom key but that did not help. I've also turned the add-on off and on after starting TB.

This is a new problem in the last week or so.

Anyone else having this problem? Any suggestions?

Using version 3.0.4. TB 78.12.0 (32-bit)

**Comment by hkclark** [comment] 2021-07-28 22:38
I'm having this as well.  I'm Win 10 on TB 78.12.0 (32-bit) & Nostalgy++ 3.04.  Thanks.

**Comment by rjbutera** [comment] 2021-07-29 14:58
I'm having this as well. I'm on TB 78.12.0 (64-bit) & Nostalgy++ 3.0.4  on Linux 5.4.17-2102.203.6.el7uek.x86_64.
This started when Nostalgy++ auto updated to 3.0.4.

**Comment by ZogsterJack** [comment] 2021-08-02 13:00
Have exactly this problem on TB 78.12.0 (64 bit) & Nostalgy++ 3.0.4 updated on 23th July
The problem started after the update but I haven't had the time to investigate the issue until now.

**Comment by opto** [comment] 2021-08-02 14:55
we don't want the keys in calendar or events etc. So they are enabled in mailTabs, only.

If this did change for you (sorry, I didn't test in a tab), then TB seems to have redefined what is a mailTab. So it seems a tab with a message in it is treated differently from the message list.

I will investigate whether there is a criterion that separates a tab with a message from other tabs and then will bring this back, if possible,

**Comment by rjbutera** [comment] 2021-08-02 15:16
I didn't see anyone mention it in this thread, but rolling TB back to 2.3.1 does fix the issue.

**Comment by hkclark** [comment] 2021-08-02 15:28
@opto Thank you so much for all your work on Nostalgy!  It's really great to see it thriving.  It's such a great addon.

**Comment by opto** [comment] 2021-08-02 17:13
thanks for the info with 2.3.1.
Problem is, 2.3.1 does not work with TB 78 64 bit, only with 32 bit. That is because 64 bit does not send the notification for mailTab.

So all this was changed, together with official TB people, and it seems the new way to do it does not recognise the mail in tabs.

**Comment by rjbutera** [comment] 2021-08-02 18:05
> Problem is, 2.3.1 does not work with TB 78 64 bit,

@opto  Is that problem only on windows?
I was using 2.3.1 and didn't notice any issues (and now went back to 2.3.1) with 64 bit TB 78.12.0 (thunderbird-78.12.0-2.0.1.el7_9.x86_64) on 64-bit Linux (5.4.17-2102.203.6.el7uek.x86_64).

**Comment by opto** [comment] 2021-08-02 21:47
mainly linux and mac.

It seems to depend on processor speed, ram etc. I suspect the tab activated message comes in all TB, but in some, there is a timing problem and we cannot receive the internal message

**Comment by Izwbusr** [comment] 2021-08-13 23:54
I am having the same or very similar problem.  Here are the details:


Nostalgy++ Version 3.0.4
Thunderbird Version 78.13.0 (32-bit) AND
Thunderbird Version 91.0 (64-bit)

- Thunderbird starts with Nostalgy shortcut keys working properly.
- When viewing a tab with emails, shortcuts continue to work.
- If an email is opened and then closed, the shortcuts no longer work.  It is as though keys are de-registered.  For example, if 's' saves the message, after opening and closing an email, 's' now stars the email.  If another key saves the message, after closing an email, it simply fails.
- Clicking on another tab and back to the original tab fixes the problem and shortcut keys work again.

**Comment by Izwbusr** [comment] 2021-08-17 22:00
> 
> 
> I am having the same or very similar problem. Here are the details:
> 
> Nostalgy++ Version 3.0.4
> Thunderbird Version 78.13.0 (32-bit) AND
> Thunderbird Version 91.0 (64-bit)
> 
>     * Thunderbird starts with Nostalgy shortcut keys working properly.
> 
>     * When viewing a tab with emails, shortcuts continue to work.
> 
>     * If an email is opened and then closed, the shortcuts no longer work.  It is as though keys are de-registered.  For example, if 's' saves the message, after opening and closing an email, 's' now stars the email.  If another key saves the message, after closing an email, it simply fails.
> 
>     * Clicking on another tab and back to the original tab fixes the problem and shortcut keys work again.

Further to this, the problem only occurs when the email tab is NOT the first one.

**Comment by opto** [comment] 2021-08-22 15:40
please see whether the solution in #121 works for you. That is in releases, version 3.0.7.

I switched off the 'tab recognition' as it doesn't seem to be reliable.

thanks,

Klaus

**Comment by Izwbusr** [comment] 2021-08-23 00:03
Yes.  The problem is fixed with version 3.0.7. Thanks so much!

PS I am a thankful contributor!  Thanks for your hard work.

**Comment by rjbutera** [comment] 2021-08-23 14:57
Works for me too.  Thanks!

Bob

**Closed** 2022-02-17 19:37 UTC
Labels: bug, enhancement, resolved
