### ISSUE TITLE
mouse gestures ... disabling or modifying

### ISSUE THREAD

**Issue by mewalter** [opto/nostalgy-xpi#155] opened 2022-02-16 23:37 UTC
Hi, I frequently grab messages and move them to folders in the left folder pane. It seems that with the new mouse gestures, if I move a little up for a little down (instead of straight to the left), I am doing a mouse gesture that sends messages into my "last used" folder. I'm constantly having to go move those messages back. Is there a way to disable mouse gestures? Or is there a way to change its behavior? I like the concept, but it is currently not working for me and creating some chaos. 
Running TB 91.6.1 and Nostalgy++ 3.2.16. 
Thanks!

**Comment by opto** [comment] 2022-02-17 07:44
thanks for the comment. Never happened to me, but it is a valid remark.

Solutions: a) switch off in options b) longer distance for mouse gesture c) only use as mouse gesture if staying for 0.5 sec in the new position
d) other ideas?

I will see what can be done, other than a).

I think you can get the messages back by undo

**Comment by mewalter** [comment] 2022-02-17 22:32
Thanks! I think that -b- is interesting option, but it is not useful at the top of the message pane unless you can define distances anywhere in the TB window. -c- might also be useful. Does it make sense to give adjustable settings for both -b- and -c- in options? Maybe that makes everything too cluttered? I don't really know how this works, but is it possible to drag up _and_ to the right or down and to the right? I'm on a PC so maybe a right-click drag? Or a different modifier (shift)? I usually always have my left hand on the keyboard, so I think I might lean towards this last idea if it is feasible. 

I do like the feature, but for some reason I seem to be losing control of it frequently. I actually feel like it sometimes happens as I am just moving the mouse (without clicking on a message) back into the message pane after having dragged a message to a folder ... it might be that this is just the residual effect of the initial gesture. It happens very fast. I'll continue to monitor and write again if there is an unexpected behavior. 

I had not thought of undo. I just tried it and it _seems_ to me that it will NOT undo a move done with mouse gestures. When I moved a message by dragging it and then move a message with a mouse gesture, the undo command will only bring back the message that was moved with the drag action. Interesting. 

Thanks for this extension (and others) that you put so much of your time into.

**Comment by mewalter** [comment] 2022-02-18 03:04
After further investigation, there seems to be a bug or something with my setup. 

If I take the top message in the message pane and drag it over to a folder, the 2nd message in the message pane will be moved to my preferred Nostalgy folder. 

I am not sure if this is reproducible for you. If not, I guess I can go into more details on my setup. I do sort message by date so that the newest message is at the top of my message pane. Below are the other extensions that I have installed and enabled. 

![2022-02-17 19_01_22-Window](https://user-images.githubusercontent.com/26728973/154609521-4e240fef-a9fd-470d-a005-a273938d5677.png)

**Comment by dragosdobrota** [comment] 2022-02-18 08:51
Got the exact same behavior: move mail#1 with **mouse** and mail#2 below it gets moved to the **preferred location** of mail#1.
I just reproduced it a couple of times.

**Comment by opto** [comment] 2022-02-19 18:18
can that be mouse up bounce? It works here.

I have not set inMove to false directly after the first move, maybe that helps (it was on a timer last version)  

for move > 100 messages and mouse up bounce for mouse gesturees, please try: https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.18

**Comment by mewalter** [comment] 2022-02-20 06:16
The fix in v3.2.18 seems to have resolved the problems I was having with mouse gestures. Thanks for attending to is so quickly.

**Comment by solopa** [comment] 2022-02-21 08:07
Thanks for your work, @opto. I've tried that 3.2.18 and the Nostalgy addon disappeared from my TB! I mean, it is in the addon's section, it is enabled, after installing the welcome screen of the 3.2.18 version showed, but it doesn't appear in the menus and the shortcuts doesn't work. Even in its addon screen, the monkey wrench icon (the one that appears between the "enable/disable" switch and the three dots) is missing.

**Comment by opto** [comment] 2022-02-21 08:13
thanks for the info. Which OS and TB version?

**Comment by solopa** [comment] 2022-02-21 08:43
Sorry for the lack of information. I've tried to find a log or something, but I couldn't find anything useful (console doesn't show anything). Please, tell me if I can provide them.

OS: Windows 10 Pro (version 21H2).
TB: 91.6.1 (64-bit)
Nostalgy++: 3.2.18

**Comment by opto** [comment] 2022-02-21 08:47
any other addons? I just tried a manual update from 3.2.17 to 3.2.18 on win 11, same TB, and everything is fine.

what I did is leave 3.2.17 installed and just installed 3.2.18 from file.

**Comment by solopa** [comment] 2022-02-21 09:03
Below you can see the addons I have installed (although I disabled all of them now to find any culprit). Is there a way to obtain a log?

Steps I've done:
- Nostalgy addon 3.2.17 installed and working.
- Disable any other addon.
- Restart Thundebird (just in case, of course Nostalgy is still working).
- Install Nostalgy 3.2.18 -> Addon doesn't work (preferences icon not showing, for example).

With 3.2.18 my addon's screen is as follows:
![Addons](https://user-images.githubusercontent.com/3253032/154921645-730b7b6b-c73d-402b-bc55-11d34514f868.jpg)

**Comment by opto** [comment] 2022-02-21 09:40
what I once had:
N++ only working after TB restart
wrench only coming up after closing/reopening the addons page

there are some bad timing problems because addons can no longer know when TB is ready on startup. So N++ could register its keys before TB registers its own keys and overwrites N++ keys, and other weid similiar stuff.

That probably changes around TB 98, there is a hold to come where addons are installed with some delay for TB to finish beforehand

**Comment by solopa** [comment] 2022-02-21 10:05
I've just tried on another system (Surface Pro + Windows 10 Home + TB 91.6.0) and I have the same problem there. I have tried to reset all the Nostalgy settings (I even deleted all the nostalgy lines in prefs.js before starting TB to see if the problem was with some setting) and the result is still the same. Restarting, closing/reopening the addon's page, etc. didn't work, either.

For the time being I'll revert to a previous version. I hope you can find the problem and that Mozilla adds that delay to fix things a little bit.

Thank you very much for your patience and, specially, for your time developing this addon under these circumstances (the Mozilla addon developing ecosystem).

**Comment by mewalter** [comment] 2022-02-21 16:49
3.2.18 is working for me. I just did a reboot to make sure that nothing broke and it was ok. I had also simply installed from the file downloaded from github. At the time 3.2.17 was still running. One difference in my setup is that I am running 91.6.1 in 32-bit.

**Comment by ThomasHeinrichSchmidt** [comment] 2022-03-29 11:59
I have the same problem as @mewalter, @solopa, and @dragosdobrota. I'm using N++ version 3.2.17 as installed by Thunderbird 91.7.0.
But for me it occurs every time I **drag a message into the Windows Explorer** to copy it to some folder on my disk. I normally do not mouse drag a message to another mail folder but I'm using N++ shortcut keys to move it. 
It is quite annoying that the message "disappears" from the current mail folder when dragging it into Explorer. It also seems not to happen always but in about 90% of the cases. I can also not confirm that Edit / Undo will bring the mail back to its original folder. I have to manually move it back.
Please introduce your proposed solution _a) switch off in options_ as I would never use a mouse gesture to move a mail to the "Shift+S" folder. I'm so much faster using Shift+S, for me using keyboard shortcuts is the whole raison d'être of N++.

**Comment by opto** [comment] 2022-03-29 12:08
this version has a new way to wait for TB startup. Previously, we didn't quite know when TB was finished to start, and TB started the addon activation parallel to its own start, before it itself was finished starting, thus creating weird timing problems.

John from TB looked at startup and proposed what now is in this version: https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.17

does that help?

Klaus

**Comment by ThomasHeinrichSchmidt** [comment] 2022-03-31 10:36
No , v3.3.17 does not help. It still moves the mail message to the "suggested folder" (Shift+S) if I drag the mail to a Windows Explorer folder. I only thought that v3.3.17 had helped because I had not yet defined a "suggested folder" after Thunderbird restart.
Please add a switch in options to disable "mouse gestures".

**Comment by opto** [comment] 2022-04-12 19:28
gestures can be disabled here: https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.19, please go to options.

**Closed by opto** 2022-04-12 19:28 UTC
Labels: bug, enhancement

**Comment by ThomasHeinrichSchmidt** [comment] 2022-04-13 08:32
Thank you opto ☀️
works like a charm ✔
![manage_emails_nostalgy_pp_3 3 19-tb](https://user-images.githubusercontent.com/8068047/163133195-bf389130-a259-44bb-85c8-7418702e3b5b.jpg)
