### ISSUE TITLE
Thunderbird is freezing when selecting a message

### ISSUE THREAD

**Issue by sphh** [opto/nostalgy-xpi#134] opened 2021-11-09 08:46 UTC
I updated the add-on from 3.0.8 to 3.0.11. When I then select a message in the list pane, Thunderbird freezes: I cannot select anything, cannot switch to a different window, I cannot even close Thunderbird. If I wait a very, very long time, Thunderbird becomes responsive again – until I select the next message.

v3.0.8 was working fine.

This looks different to #130.

Thunderbird: 78.13.0 (64-bit)
System: Linux Mint 20.2
3 IMAP mailboxes with many folders

**Comment by jxcx** [comment] 2021-11-10 06:21
I have a similar problem on Ubuntu 20.04. Thunderbird freezes trying to display any message and never becomes responsive again. Verified with a clean new POP profile and no other extensions. The last working version for me is 3.06.

**Comment by dmusican** [comment] 2022-01-02 14:20
I keep getting random freezing, and reverting to the last few versions hasn't helped. Based on @jxcx's suggestion, I'm backing off to 3.0.6. Hopefully that helps.

**Comment by internationils** [comment] 2022-01-05 14:36
I am seeing the same ... was looking into a different issue and saw it https://github.com/opto/nostalgy-xpi/issues/137 ... I will continue the debugging here

**Comment by dmusican** [comment] 2022-01-05 14:40
FYI, I've been really happy since reverting to 3.0.6. I haven't had a single lockup since, where it was happening to me at least once a day with the newer versions.

**Comment by internationils** [comment] 2022-01-05 15:54
@dmusican @opto I just tried 3.0.6, .8, .10 and .11 ... the mail selection works in .6 and .8, and slows for .10 and .11 (there is on .9 release)

Maybe try 3.0.8 again for a while?

**Comment by opto** [comment] 2022-01-06 19:34
this might (?) be caused by #133?
Soon, I will add the possibility to switch that search off, or maybe have extra debug messages for that.

**Comment by sphh** [comment] 2022-01-06 19:56
I remember that [mailmindr](https://mailmindr.net/en/) add-on had a similar problem. Arnd said, that the problem is, that mailmindr is searching for mails containing a mailmindr reminder in all folders in all accounts (if I understood him correctly). In the current implementation it still uses a lot of CPU time, when looking for those mails, but Arnd managed that does not lock anymore. I have absolutely no idea, if this is caused by the same ‘problem’, it's Just An Idea …

**Comment by opto** [comment] 2022-01-06 22:38
please try 3.1.3 https://github.com/opto/nostalgy-xpi/releases/tag/v3.1.3

swich off the ption for conversation /thread search if necessary

**Comment by sphh** [comment] 2022-01-06 22:56
:clap: I have both `Use statistical prediction` and `Suggest folder of related conversation` on and the behaviour is crisp: As soon as I select a message it is displayed and Thunderbird stays responsive. Thanks!!

If it were up to me, this issue could be closed.

**Comment by internationils** [comment] 2022-01-07 07:13
Tried 3.1.3 on 91.3.1 .... works for me. `Suggest folder of related conversation` is on however, and it still works in real-time ...

For me this issue can be closed as well.

**Comment by opto** [comment] 2022-01-07 10:57
thanks

**Closed by opto** 2022-01-07 10:57 UTC
