### ISSUE TITLE
Copy messages with 'c' not working 91.6.1 (32 bit) Windows 10 Version 3.2.17

### ISSUE THREAD

**Issue by fespuela** [opto/nostalgy-xpi#167] opened 2022-02-23 14:24 UTC
Hi,

Although move and go to messages with keys works, the hotkey copy function does not work. It seems that it does, but the message is not copied.

Thunderbird 91.6.1 (32 bit) 
Windows 10 
Manage Emails/ Nostalgy++Version 3.2.17

Regards

**Comment by vanous** [comment] 2022-02-24 09:35
Issue confirmed here on Linux too.

Nostalgy++Version 3.2.17
Thunderbird 91.6.1

**Comment by opto** [comment] 2022-02-24 09:39
is this with more than 100 messages or all the time?

**Comment by opto** [comment] 2022-02-24 09:40
I might revert back from webextension technology to the old version because we also don#t seem to have undo capability yet.

**Comment by vanous** [comment] 2022-02-24 09:51
@opto it is even with just a single message...

**Comment by sinkva** [comment] 2022-02-28 05:23
Confirmed on MacOS, also.

MacOS 11.6.1 (Big Sur)
Thunderbird 91.6.1 (64-bit)
Nostalgy++ 3.2.17
Single and (quantity) two messages at a time

**Comment by karlbu** [comment] 2022-02-28 14:55
Same here.

**Comment by Olifair** [comment] 2022-03-01 07:16
I'm running TB 91.6.1 32bit and Nostalgy++ 3.2.17 on a windows 10 64bits laptop and I do not seem to have any problem, s,g,b and shift+s,g,b and alt+g work as expected from the main window (and I'm not using any folder filters, always showing all folders).  I'm having a few other extensions installed (Copy Message ID, Copy Sent to Current, FiltaQuilla, ToggleHeaders) and they do not seem to interfere.  I have tried to use the keys from the IMPA inbox to other IMAP folder and to local folders, all working. I thus wonder where the problem that people describe above lies ?

**Comment by vanous** [comment] 2022-03-01 08:09
Problem is with 'c' (message copy), as indicated in the title.

**Comment by Olifair** [comment] 2022-03-01 13:05
@vanous  oups, sorry, for some reason didn't see that this was about copy, and yes, I can confirm that it isn't working here either.

**Comment by bsgcic** [comment] 2022-03-01 14:54
Hi,
First, a huge thank you to opto and the Nostalgy++ team.  This is an indispensable add-on.  Your doing a fantastic job!
This bug is absolutely real, and from above appears to be present in all platforms.
My system is:  Ubuntu 20.04LTS (all updates applied), Thunderbird 91.5 (64-bit).  This has been a huge issue since version 3.2.16 and also 3.2.17.  I finally, yesterday realized that this problem was inherent in the Nostalgy++ code and appeared in 3.2.16 (January) which kind of has me in a bind because I had been assuming all the copying that I was doing was working and now, I know that there are tons of critical emails not correctly duplicated in different folders that I need them.  Anyway, I removed 3.2.17 (I had also tested with replacing it with 3.2.16) and replaced it with 3.0.7 which works.
Please note, that there is in addition issue in Thunderbird itself (and possibly Nostalgy++ 3.2.16 and 3.2.17) where (1) If I press CTRL and drag to another folder, it moves instead of copies; and (2) If I do "C" for copy, it instead moves it.  That can happen before or after attempting to initially just do a "C" copy.

Hope this helps, thank you again for this wonderful add-on, and keep up the great work.

**Comment by opto** [comment] 2022-03-01 17:00
this is a really bad bug, because: it is working here. At least the drag 
an email with ctrl, it does copy.


As for Nostalgy copy, I have a hunch what might be (sometimes) wrong and 
will upload a test version soon.


Klaus

**Comment by bsgcic** [comment] 2022-03-01 17:22
Hi Klaus,
Thank you for your comment.  Yeah, these types of intermittent bugs are indeed some of the toughest - always the hardest for me when I'm developing.  It was very intermittent.  I don't recall the series of steps that triggered it.  I remember it was after I was trying to deal with the other problem on copying an email.  I encountered that perhaps 3 or 4 times and on different days. Then I just started to use the right-click Copy-To which was dependable.

**Comment by opto** [comment] 2022-03-01 19:38
please try this https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.22

**Comment by fespuela** [comment] 2022-03-01 20:35
I have done a speed test, and seems addon don't work. Not appears options in the addon menu (add shortcut keys and other options), and when press 'c' 's' or another shortcut key Thunderbid works like the addon not be insalled.

Tomorrow I will be able to try it more calmly

**Comment by fespuela** [comment] 2022-03-02 10:17
Definitely I can't get the addon to work in this version (3.2.22).

When I install the addon, not appears options icon. And when restart, addon dissapear:
https://imgur.com/URlT7BN

When press 'C' appears standard thunderbird option:
https://imgur.com/oBrBkVg

**Comment by opto** [comment] 2022-03-02 20:19
there was a bug in copy implementation, I do not remember whether already fixed in 3.2.22.

This https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.24  reverts back to the old copy mechanism so that we get back undo, which is not implemented yet in webextension code.

options icon does appear here (also in 3.2.22). If not, you an use tools->Nostalgy++

**Comment by k11i** [comment] 2022-03-03 10:31
Just installed https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.24 on Linux 91.6.1 (64-bit) resulting in no functionality at all.

Icon to preference vanished from extension list and none of the usual shortcuts work anymore. 

(BTW: after it had been working for some time again, in the last few days there has also been a regression, that shortcuts only work after changing tabs away and back again. But I'm sorry, I did not look which version I had installed then).

**Comment by juancarretero** [comment] 2022-03-07 13:44
Clearly, this is a significant issue for all platforms.  Does anyone know when this started?  I have been using this tool for quite some time now and wondering how many copies I have been missing.  If this has been going on for over 12 days (when the first post in this thread was created) it may mean several hours of work for me to recover all the missing copies of messages.

**Comment by fespuela** [comment] 2022-03-07 16:12
Currently i'm using version 3.1.3 and works perfectly.

**Comment by opto** [comment] 2022-03-07 16:16
this started when trying to use the new webextenson version for copy/move, which also has no undo.

Please use the new version under releases here on github  https://github.com/opto/nostalgy-xpi/releases/tag/v3.2.24

**Comment by juancarretero** [comment] 2022-03-13 13:31
Thank you opto!!

I am working on Ubuntu 21.10 and I have not been able to instal version 3.2.24 on top of the default (version 3.2.17 through the Add-ons Manager).  Can anyone guide me to a _how-to guide_ that would help me?

**Comment by rjbutera** [comment] 2022-03-15 18:38
Hi Opto,
V3.2.24 has fixed the issue for me.  Thanks!

Bob Butera

**Comment by opto** [comment] 2022-03-21 13:51
please try the newest release. I tested both on win 11 and Ubuntu 20:

please try this https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.2

**Closed by opto** 2022-03-21 13:51 UTC

**Comment by bsgcic** [comment] 2022-03-24 12:50
Hi Opto,
    Thunderbird just updated on Ubuntu 20.04lts to
        91.7.0 (64-bit) and I installed v3.3.2.  So far looking good.  I
        was able to copy an email using the 'c' key, move the copied
        email using the 'm' key, copy an email pressing ctrl and
        dragging to another folder, and move the email dragging.  I'll
        keep this active and will let you know if I find anything.
    Thank you for your excellent work!
        Jeff
    
    On 3/21/22 9:51 AM, opto wrote:
    
    
      
      please try the newest release. I tested both on win
        11 and Ubuntu 20:
      please try this https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.2
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        You are receiving this because you commented.Message
          ID: ***@***.***>
      [
        {
        ***@***.***": "http://schema.org",
        ***@***.***": "EmailMessage",
        "potentialAction": {
        ***@***.***": "ViewAction",
        "target":
"https://github.com/opto/nostalgy-xpi/issues/167#issuecomment-1073922715","url":
"https://github.com/opto/nostalgy-xpi/issues/167#issuecomment-1073922715",
        "name": "View Issue"
        },
        "description": "View this Issue on GitHub",
        "publisher": {
        ***@***.***": "Organization",
        "name": "GitHub",
        "url": "https://github.com"
        }
        }
        ]

**Comment by rjbutera** [comment] 2022-10-11 06:55
> please try this https://github.com/opto/nostalgy-xpi/releases/tag/v3.3.2

On Windows 10, after installing 3.3.2, any time I restart TB, copy messages
with 'c'
(or anything else) does not work in an open mail tab unless I
- close the open mail message tab
- go to add-ons and disable and re-enable Nostalgy
- re-open the mail message
and now copy messages with 'c' will work

Bob Butera
