### ISSUE TITLE
When forwarding Email Body gets focus rather than 'To'

### ISSUE THREAD

**Issue by dbergol** [opto/nostalgy-xpi#197] opened 2022-11-17 07:21 UTC
HI

I am using TB 102.4.2 64bit on Windows 10 and 11, latest Nostalgy++ 3.6.12
When clicking 'forward' to forward a message, then the cursor jumps to the message body and does NOT stay in 'To'. When disabling Nostalgy++ and restarting TB, it works as 'usual' and expected, re-enabling Nostalgy++ shows thessue again.

Any idea?

Thanks, Daniel

**Comment by pavhofman** [comment] 2022-12-02 08:58
I have the same problem, Nostalgy 3.6.11. Thanks a lot for looking at possible solutions.

With regards,

Pavel.

**Comment by pavhofman** [comment] 2022-12-02 09:02
Actually the problem is fixed in the latest 3.6.13, thanks a lot for the great support!

Pavel.

**Comment by dbergol** [comment] 2022-12-02 09:27
Big thanks from me as well for the fix!!

Best, Daniel

**Closed** 2022-12-02 09:28 UTC
