### ISSUE TITLE
"g" jumps to folder, but folder pane jumps to first account, not folder

### ISSUE THREAD

**Issue by SKelem** [opto/nostalgy-xpi#118] opened 2021-07-21 05:49 UTC
"g" used to list folders matching the search string. Then, clicking on one of the candidates changes the Subject pane to the folder, and scrolled the Folder pane to the folder.
Now, in version 3.0.1 (TB 78.11.0), "g" no longer changes the Folder pane to the selected folder.
That functionality is important to me. Is there another key that will change the Folder pane to the selected folder?

**Comment by SKelem** [comment] 2021-07-28 18:38
The Nostalgy Help says "Because of the g command, the folder pane becomes thus much less useful, and it can be hidden with the l shortcut."

I strongly disagree. I, very frequently, want to jump to the folder in the folder pane so that I can:

- right-click and select folder properties
- right-click and select Remove Duplicates
- right-click and set Mailbox Alerts
- see the adjacent folders, which are related to the email I'm looking at.
- Move the folder somewhere else in the folder hierarchy

**Comment by cjholly** [comment] 2021-07-28 20:03
OK, but all you have to do is press L to open the folder pane, so I 
think I am missing your point. You can then even hit Esc-F in very close 
succession and move about the folder pane with the keyboard and never 
have to touch the friggin' mouse! Nostalgy++ is very cool, indeed!  --Chris

**Comment by opto** [comment] 2021-07-28 20:57
>"g" no longer changes the Folder pane to the selected folder.

It does here, so what is your OS, TB version, 32 or 64 bit, is it an extra fast PC?
I tested on Win 10 64 bit both with 78.12.0 32 bit and 64 bit. (and TB 91.0b2)

**Comment by SKelem** [comment] 2021-07-28 21:47
Ooops. Forgot the OS

Ubuntu Linux 21.04.

opto wrote on 7/28/21 1:58 PM:

**Comment by SKelem** [comment] 2021-07-28 21:51
Okay, hitting "l" (lower-case L) twice works...Once to close the folder pane and again to open it up again.

I would rather that jumping to the current folder would be part of "g"'s behavior, but this works. The default behaviour of "g" jumping to the very first account is annoying. I wish there were a way to have an option to either go to the current folder in the folder pane or do nothing in the folder pane.

Steve

cjholly wrote on 7/28/21 1:04 PM:

**Comment by wernerfb** [comment] 2021-11-02 15:21
For me "g" does not work if folder I want to go to is not in folder list (e.g. because I only view folders with unread messages).

Windows 10, TB 91.2.1 32 bit, Nostalgy++ 3.0.4

**Comment by opto** [comment] 2021-11-02 20:38
switching the view will come (e.g. from unread to all).

Klaus

**Comment by opto** [comment] 2021-11-03 23:45
I can confirm that g selects the new folder or account, but does not scroll there if it is in another account,
In 3.0.10, H now does the scrolling. I will check how to combine the two to get back the old behaviour

**Comment by opto** [comment] 2022-02-17 19:36
duplicate of #137 (originally, that was a duplicate of this, but its title is better ...)

**Closed by opto** 2022-02-17 19:36 UTC
Labels: bug
