### ISSUE TITLE
Compose Dialog Settings for CC and BCC have no Effect 102.0.3

### ISSUE THREAD

**Issue by szmontsaroff** [opto/nostalgy-xpi#187] opened 2022-07-25 04:33 UTC
Setting "Always show CC/BCC line in compose has no effect on this release of thunderbird.

**Comment by opto** [comment] 2022-08-02 21:21
found the change in TB, working here already

**Comment by szmontsaroff** [comment] 2022-08-16 04:35
Does this mean it will be supported in a future release?

**Comment by reagle** [comment] 2022-08-18 12:00
I'm wondering if this might be related to #186 ?

**Comment by hkclark** [comment] 2022-09-17 13:05
I'm having this same issue.
@opto When you say "working here already", do we need to do something on our end to get your fix?  I'm at 3.6.1 (I'm letting the normal upgrade process in TBird upgrade me when it finds a new version).
Thanks.

**Comment by opto** [comment] 2022-10-02 21:18
I am confused. It is not working in the version from ATN, so maybe I have not yet uploaded it, or maybe the compose dialog has changed again (they changed function names and ids etc. for 102).

**Comment by reagle** [comment] 2022-10-03 13:25
I'm not sure where this setting is, but I think it's specific to account settings and I have cc/bcc ticked, but not addresses, and I think this meant always include those headers, but it doesn't in  thunderbird 102.3.1 .
![SCR-20221003-d23](https://user-images.githubusercontent.com/596814/193588891-32bb6942-7d5d-4188-af8b-f24e62b94c7c.png)
![SCR-20221003-d1w](https://user-images.githubusercontent.com/596814/193588892-a1459308-dafc-48d0-8a67-d4071bf313aa.png)

**Comment by opto** [comment] 2022-10-04 12:29
please try this: https://github.com/opto/nostalgy-xpi/releases/tag/v3.6.3

@reagle: it is not that. This means a setting in the options where you can decide to always show the cc or bcc lines in compose dialog.

**Comment by hkclark** [comment] 2022-10-04 12:38
@opto Works great for me!  You are a hero.  Thank you!

**Comment by hi5** [comment] 2022-10-07 17:00
> please try this: https://github.com/opto/nostalgy-xpi/releases/tag/v3.6.3
> 
> @reagle: it is not that. This means a setting in the options where you can decide to always show the cc or bcc lines in compose dialog.

When I turn "show CC" on and I hit reply (all) on an email the caret is in the "TO:" field and not in the body - if I turn it off again the caret is in the body of the email and I can start typing as usual.

**Comment by hkclark** [comment] 2022-10-07 17:16
> When I turn "show CC" on and I hit reply (all) on an email the caret is in the "TO:" field and not in the body - if I turn it off again the caret is in the body of the email and I can start typing as usual.

Yes, I have noticed that "slight annoyance" as well.  But otherwise, it's working great for me.

**Comment by mewalter** [comment] 2022-10-10 17:27
> 

Same issue for me with the cursor ending up in the "To" field. Just need to remember to hit tab a few times to get it to the body. Benefits of Nostalgy++ far outweigh this minor inconvenience.

**Comment by opto** [comment] 2022-10-10 20:35
yes, thanks for reporting.
 Can it be fixed? Depends on how to distinguish in the code reply (all) from write, where it would make sense to have cursor in to.

**Comment by hi5** [comment] 2022-10-11 16:45
Perhaps: `IF subject.hascontent() THEN setfocus.body() ` the reason being that a reply (all) would always have something in the subject line where as writing a new email in many case won't have one yet (e.g. subject is empty) - of course one can think of cases where the subject line does have content and there is no TO but my guess that would be rare.

**Comment by opto** [comment] 2022-10-11 19:49
please try this. It also revives esc esc to get into the body: https://github.com/opto/nostalgy-xpi/releases/tag/v3.6.5

**Comment by mewalter** [comment] 2022-10-12 00:16
This definitely works when using reply or reply-all. Thanks. 

Minor problem is that when using Forward, it also sets focus in the message body. For Forward the expected behavior would be to set focus in the To field. Looks like the approach of using IF subject.hascontent() does neglects the fact that a forwarded message will have a subject but has a blank To field. Sorry, 

I am completely ignorant with the code. Is there are "IF to.hascontent()" call? If so, is that the way to go?

**Comment by opto** [comment] 2022-10-12 08:30
yes and no, because there are the 'crazy' pills showing the addresses.
So one would do:?
if to empty and subject present, go to to?

**Comment by opto** [comment] 2022-10-12 08:31
you still can go there by esc followed by t

**Comment by hi5** [comment] 2022-10-12 16:39
> please try this. It also revives esc esc to get into the body: https://github.com/opto/nostalgy-xpi/releases/tag/v3.6.5

Works for me, thanks 👍 as does esc-esc, esc-t, esc-c

With regards to forwarding
> if to empty and subject present, go to to?

sounds reasonable if possible

**Comment by opto** [comment] 2022-11-08 22:26
3.6.11 is in review so close this

**Closed by opto** 2022-11-08 22:26 UTC

**Comment by opto** [comment] 2022-11-09 12:57
for forward focus issue:  https://github.com/opto/nostalgy-xpi/releases/tag/v3.6.13
